# Generated by Django 3.2.6 on 2021-09-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='아이디')),
                ('username', models.CharField(max_length=50, verbose_name='이름')),
                ('password', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('useremail', models.EmailField(max_length=254, verbose_name='이메일')),
                ('useraddress', models.CharField(max_length=300, verbose_name='주소')),
                ('registerTime', models.DateTimeField(auto_now_add=True, verbose_name='가입날짜')),
                ('gender', models.CharField(choices=[('M', '남성(men)'), ('W', '여성(women')], max_length=1, verbose_name='성별')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품')),
            ],
        ),
    ]
