# Generated by Django 3.2.6 on 2021-09-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floweruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='floweruser',
            name='username',
        ),
    ]
